// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcvQYT34x00-6oAEvkNiFXzZPG4_TBAS0',
    appId: '1:305785982111:web:f92251a0666adbb469a6aa',
    messagingSenderId: '305785982111',
    projectId: 'cityguide-fd47a',
    authDomain: 'cityguide-fd47a.firebaseapp.com',
    storageBucket: 'cityguide-fd47a.firebasestorage.app',
    measurementId: 'G-Q4CHDDK0D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4nQDl1WFwOJ8UG1HcGfcHImhXowhmS00',
    appId: '1:305785982111:android:85a8272e2e42e16169a6aa',
    messagingSenderId: '305785982111',
    projectId: 'cityguide-fd47a',
    storageBucket: 'cityguide-fd47a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Gp6mrDoE1go2SH88S7o9stfsBoEsP6M',
    appId: '1:305785982111:ios:7e34fc686b968f5669a6aa',
    messagingSenderId: '305785982111',
    projectId: 'cityguide-fd47a',
    storageBucket: 'cityguide-fd47a.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Gp6mrDoE1go2SH88S7o9stfsBoEsP6M',
    appId: '1:305785982111:ios:7e34fc686b968f5669a6aa',
    messagingSenderId: '305785982111',
    projectId: 'cityguide-fd47a',
    storageBucket: 'cityguide-fd47a.firebasestorage.app',
    iosBundleId: 'com.example.cityGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcvQYT34x00-6oAEvkNiFXzZPG4_TBAS0',
    appId: '1:305785982111:web:7a839e163f34b12b69a6aa',
    messagingSenderId: '305785982111',
    projectId: 'cityguide-fd47a',
    authDomain: 'cityguide-fd47a.firebaseapp.com',
    storageBucket: 'cityguide-fd47a.firebasestorage.app',
    measurementId: 'G-FSHD1FCL92',
  );
}
